version: '3'
services:
  luxparkings:
    build: .
    env_file:
      - .env
    depends_on:
      - "elasticsearch"
  elasticsearch:
    image: "elasticsearch:7.9.1"
    ports:
    - "9200:9200"
    - "9300:9300"
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=true
    volumes:
      - "esdata:/usr/share/elasticsearch/data"
  kibana:
    image: "kibana:7.9.1"
    ports:
      - "5601:5601"
    env_file:
      - .env
    depends_on:
      - "elasticsearch"
    environment:
      - ELASTICSEARCH_USERNAME=kibana
    volumes:
      - "eskibana:/usr/share/kibana/data"
volumes:
    esdata:
        external: true
    eskibana:
        external: true